probe-checks: add icmp check support
uptime-com/terraform-provider-uptime pull request #26
Opened 2023-05-27 09:45 UTC by pinotelio

This commit adds the support of ICMP checks/probes.

Signed-off-by: pinotelio [ahmadreza.mollapour@gmail.com](mailto:ahmadreza.mollapour@gmail.com)

2023-05-27 09:47 UTC, pinotelio commented
PTAL: @kylegentle @liamkinne

2023-05-27 13:09 UTC, liamkinne commented
@pinotelio Code looks good to me. Don't have the facilities to to test against the actual API. I don't have write access and likely neither does Kyle so you may have to raise a support request to get one of the Uptime guys to look at this.

2023-05-28 20:40 UTC, mikluko commented
@pinotelio LGTM, but it requires acceptance tests coverage. Check out `*_test.go` for reference.

2023-05-31 08:17 UTC, pinotelio commented
> @pinotelio LGTM, but it requires acceptance tests coverage. Check out `*_test.go` for reference.

@mikluko Please take a look. The test coverage and proper docs have been added.

2023-06-22 22:55 UTC, pinotelio commented
Any update guys?
@mikluko @liamkinne @kylegentle

2023-06-22 23:18 UTC, kylegentle commented
@pinotelio, thanks for contributing this improvement!

I haven't looked at the project in a long time, and unfortunately I don't have access to approve or merge PRs. Mikhail seems like the right person to approve.

On a separate note, it would be helpful for someone from Uptime to flesh out the Contribution Guidelines section in the README, and set expectations for how PRs will be handled.

2023-06-23 08:52 UTC, bazzisoft commented
@pinotelio We'll do our best to look at this next week, there's a bit of a tricky situation where we're on the verge of releasing a major update v2.0 of the provider (it's been in beta for a while) which has some very significant code changes, so we'll need to check how we can port this over to that too. We'll keep you posted.

@kylegentle Thanks for your comment & good idea re the guidelines, we'll work on getting those into the README!

2023-06-26 09:14 UTC, mikluko requested changes

2023-06-26 09:14 UTC, mikluko commented on uptime/resource_uptime_check_icmp_test.go
> +func TestHeaderConversion(t *testing.T) {
Is this test required here or is it just a copy-paste atifact?

2023-06-26 09:14 UTC, mikluko commented on uptime/resource_uptime_check_icmp_test.go
> +func TestAccCheckHttpResource(t *testing.T) {
Isn't this test should be named `testAccCheckPingresource`?

2023-07-15 17:18 UTC, pinotelio commented
> @pinotelio We'll do our best to look at this next week, there's a bit of a tricky situation where we're on the verge of releasing a major update v2.0 of the provider (it's been in beta for a while) which has some very significant code changes, so we'll need to check how we can port this over to that too. We'll keep you posted.
> 
> @kylegentle Thanks for your comment & good idea re the guidelines, we'll work on getting those into the README!

Since version 2.0 has released a couple of weeks ago, it's probably best to close this pull request. I'll take a look at the fresh code changes and submit a new pull request incorporating the latest updates.

2023-07-15 17:19 UTC, closed without merging