Add Dashboard Resource
uptime-com/terraform-provider-uptime pull request #34
Opened 2023-11-16 10:08 UTC by gigovich

Add Dashboard Resource support.

2023-11-16 11:00 UTC, gigovich commented
This PR has dependency PR https://github.com/uptime-com/uptime-client-go/pull/4

2023-11-17 11:04 UTC, mikluko commented
```
=== NAME  TestAccDashboardResource_Tags
    resource_dashboard_test.go:134: Step 2/2 error: Error running apply: exit status 1
        
        Error: Provider produced inconsistent result after apply
        
        When applying changes to uptime_dashboard.test, provider
        "provider[\"registry.terraform.io/hashicorp/uptime\"]" produced an unexpected
        new value: .services_tags: planned set element cty.StringVal("ample-haddock")
        does not correlate with any element in actual.
        
        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
        
        Error: Provider produced inconsistent result after apply
        
        When applying changes to uptime_dashboard.test, provider
        "provider[\"registry.terraform.io/hashicorp/uptime\"]" produced an unexpected
        new value: .services_tags: planned set element cty.StringVal("bold-basilisk")
        does not correlate with any element in actual.
        
        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
        
        Error: Provider produced inconsistent result after apply
        
        When applying changes to uptime_dashboard.test, provider
        "provider[\"registry.terraform.io/hashicorp/uptime\"]" produced an unexpected
        new value: .name: was cty.StringVal("sadly-immense-dinosaur"), but now
        cty.StringVal("usually-evolved-boa").
        
        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
```

2023-11-17 11:10 UTC, mikluko requested changes

2023-11-17 11:10 UTC, mikluko commented on internal/provider/resource_dashboard.go
> +type DashboardResourceModel struct {
This resource should utilize `services`, `alerts` and `metrics` nested blocks instead of using corresponding attribute prefixes.

2023-11-17 11:10 UTC, mikluko commented on internal/provider/resource_dashboard_test.go
> +				ConfigDirectory: config.StaticDirectory("testdata/resource_dashboard/_basic"),
Basic test is supposed to work with absolute minimal set of options for the resource, not the full set.

2023-11-28 12:37 UTC, gigovich commented on internal/provider/resource_dashboard.go
> +type DashboardResourceModel struct {
Fixed.

2023-11-28 12:37 UTC, gigovich commented on internal/provider/resource_dashboard_test.go
> +				ConfigDirectory: config.StaticDirectory("testdata/resource_dashboard/_basic"),
Fixed.

2023-11-28 14:12 UTC, merged